# Generated by Django 3.2.6 on 2023-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20231004_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='next_date_of_administration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
