# Generated by Django 3.2.6 on 2023-09-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_healthworker_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworker',
            name='location',
        ),
    ]
