# Generated by Django 3.2.6 on 2023-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_remove_vaccine_maximum_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='recommended_age_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
