# Generated by Django 3.2.6 on 2023-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_alter_vaccine_vaccine_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_choice',
            field=models.CharField(choices=[('BCG', 'BCG - Tuberculosis - Recommended Age: Birth'), ('HepB', 'Hepatitis B - Hepatitis B - Recommended Age: Birth, 1-2 months, 6-18 months'), ('DTP', 'DTP - Diphtheria, Tetanus, Pertussis - Recommended Age: 2 months, 4 months, 6 months, 15-18 months'), ('IPV', 'IPV (Inactivated Polio Vaccine) - Polio - Recommended Age: 2 months, 4 months, 6-18 months'), ('HiB', 'HiB (Haemophilus influenzae type b) - Haemophilus influenzae type b - Recommended Age: 2 months, 4 months, 6 months, 12-15 months'), ('PCV13', 'PCV13 (Pneumococcal Conjugate Vaccine 13-valent) - Pneumococcal disease - Recommended Age: 2 months, 4 months, 6 months, 12-15 months'), ('RV', 'RV (Rotavirus Vaccine) - Rotavirus - Recommended Age: 2 months, 4 months'), ('MMR', 'MMR (Measles, Mumps, and Rubella) - Measles, Mumps, Rubella - Recommended Age: 12-15 months'), ('Varicella', 'Varicella (Chickenpox) - Chickenpox - Recommended Age: 12-15 months'), ('HepA', 'Hepatitis A - Hepatitis A - Recommended Age: 12-18 months'), ('MenACWY', 'MenACWY (Meningococcal Conjugate) - Meningococcal disease - Recommended Age: 12-15 months'), ('DTaP-IPV-HiB-HepB', 'DTaP-IPV-HiB-HepB - Diphtheria, Tetanus, Pertussis, Polio, Haemophilus influenzae type b, Hepatitis B - Recommended Age: 2 months, 4 months, 6 months'), ('Influenza', 'Influenza - Influenza (Seasonal) - Recommended Age: Annually from 6 months onwards')], max_length=32, null=True, unique=True),
        ),
    ]
